FROM mysql:5.7

# Copy the SQL dump file into the container
COPY ./database/tms.sql /docker-entrypoint-initdb.d/

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=tms
ENV MYSQL_USER=tmsuser
ENV MYSQL_PASSWORD=tmspassword

# Expose MySQL port
EXPOSE 3306