apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-app-pv-tms
spec:
  capacity:
    storage: {{ .Values.app.persistence.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.app.persistence.storageClass }}
  hostPath:
    path: "/mnt/php-data"
    type: DirectoryOrCreate