apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-app-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.app.persistence.size }}
  storageClassName: {{ .Values.app.persistence.storageClass }}