apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
        imagePullPolicy: {{ .Values.app.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.app.service.targetPort }}
        envFrom:
        - configMapRef:
            name: {{ .Values.configMap.name }}
        - secretRef:
            name: db-secrets
        env:
        - name: DB_HOST
          value: {{ .Values.database.name }}
        volumeMounts:
        - name: php-storage
          mountPath: {{ .Values.app.persistence.mountPath }}
      volumes:
      - name: php-storage
        persistentVolumeClaim:
          claimName: php-app-pvc-tms