apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
data:
  PHP_VERSION: {{ .Values.configMap.phpVersion | quote }}
  ADMIN_USER: {{ .Values.configMap.adminUser | quote }}
  DB_NAME: {{ .Values.configMap.dbName | quote }}