apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-tms
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.database.persistence.size }}
  storageClassName: {{ .Values.database.persistence.storageClass }}