apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-tms
spec:
  capacity:
    storage: {{ .Values.database.persistence.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.database.persistence.storageClass }}
  hostPath:
    path: "/mnt/data"
    type: DirectoryOrCreate