apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  DB_USER: {{ .Values.secret.dbUser }}
  DB_PASSWORD: {{ .Values.secret.dbPassword }}
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.mysqlRootPassword }}