apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-app-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: "/mnt/php-data"
    type: DirectoryOrCreate